const { nowIso } = require("../utils");
const { DEFAULT_INITIAL_PASSWORD, hashPassword } = require("../security/password");

function createSeedData() {
  const now = nowIso();
  const firstSessionStart = futureDate(5, 19);
  const secondSessionStart = futureDate(6, 14);
  const lunchSessionStart = futureDate(2, 12);
  const partySessionStart = futureDate(3, 19);
  const socialSessionStart = futureDate(4, 20);
  const scriptSessionStart = futureDate(8, 18);
  const fullSessionStart = futureDate(10, 15);
  const strategySessionStart = futureDate(11, 19);
  const cancelledSessionStart = futureDate(12, 16);
  const rpgSessionStart = futureDate(14, 18);
  const finishedSessionStart = pastDate(4, 18);
  const failedSessionStart = pastDate(2, 19);
  return {
    users: [
      {
        id: "11001",
        student_no: "2314007",
        name: "李佳璞",
        nickname: "Jiapu",
        role: "student",
        avatar: "1.png",
        auth_status: "verified",
        credit_score: 100,
        status: "active",
        tags: ["推理", "阵营", "欢乐本"],
        contact: "lijia@example.edu",
        auth_submission_name: "李佳璞",
        auth_submission_student_no: "2314007",
        auth_submission_contact: "lijia@example.edu",
        auth_submission_note: "已通过历史导入认证",
        auth_submitted_at: now,
        auth_review_reason: "",
        auth_reviewed_at: now,
        password_hash: hashPassword(DEFAULT_INITIAL_PASSWORD),
        created_at: now,
      },
      {
        id: "11002",
        student_no: "2313983",
        name: "刘砚桐",
        nickname: "YanTong",
        role: "student",
        avatar: "2.png",
        auth_status: "verified",
        credit_score: 96,
        status: "active",
        tags: ["德式桌游", "策略"],
        contact: "liuyt@example.edu",
        auth_submission_name: "刘砚桐",
        auth_submission_student_no: "2313983",
        auth_submission_contact: "liuyt@example.edu",
        auth_submission_note: "已通过历史导入认证",
        auth_submitted_at: now,
        auth_review_reason: "",
        auth_reviewed_at: now,
        password_hash: hashPassword(DEFAULT_INITIAL_PASSWORD),
        created_at: now,
      },
      {
        id: "11003",
        student_no: "2313828",
        name: "苏雨辰",
        nickname: "Yuchen",
        role: "student",
        avatar: "3.png",
        auth_status: "pending",
        credit_score: 100,
        status: "active",
        tags: ["新手友好"],
        contact: "suyc@example.edu",
        auth_submission_name: "苏雨辰",
        auth_submission_student_no: "2313828",
        auth_submission_contact: "suyc@example.edu",
        auth_submission_note: "首次提交学生证信息，等待管理员审核。",
        auth_submitted_at: now,
        auth_review_reason: "",
        auth_reviewed_at: null,
        password_hash: hashPassword(DEFAULT_INITIAL_PASSWORD),
        created_at: now,
      },
      {
        id: "11004",
        student_no: "2312194",
        name: "朱乐晨",
        nickname: "Lechen",
        role: "student",
        avatar: "4.png",
        auth_status: "unverified",
        credit_score: 92,
        status: "active",
        tags: ["剧本杀", "硬核"],
        contact: "zhulc@example.edu",
        auth_submission_name: "朱乐晨",
        auth_submission_student_no: "2312194",
        auth_submission_contact: "zhulc@example.edu",
        auth_submission_note: "已通过历史导入认证",
        auth_submitted_at: now,
        auth_review_reason: "",
        auth_reviewed_at: null,
        password_hash: hashPassword(DEFAULT_INITIAL_PASSWORD),
        created_at: now,
      },
      {
        id: "11005",
        student_no: "2314055",
        name: "陈默",
        nickname: "ChenMo",
        role: "student",
        avatar: "5.png",
        auth_status: "verified",
        credit_score: 108,
        status: "active",
        tags: ["合作", "新手", "花火"],
        contact: "chenmo@example.edu",
        auth_submission_name: "陈默",
        auth_submission_student_no: "2314055",
        auth_submission_contact: "chenmo@example.edu",
        auth_submission_note: "评测样例：高信用合作类玩家",
        auth_submitted_at: now,
        auth_review_reason: "",
        auth_reviewed_at: now,
        password_hash: hashPassword(DEFAULT_INITIAL_PASSWORD),
        created_at: now,
      },
      {
        id: "11006",
        student_no: "2314066",
        name: "赵乔予",
        nickname: "Qiaoyu",
        role: "student",
        avatar: "6.png",
        auth_status: "verified",
        credit_score: 98,
        status: "active",
        tags: ["聚会", "欢乐", "想象"],
        contact: "zhaoqy@example.edu",
        auth_submission_name: "赵乔予",
        auth_submission_student_no: "2314066",
        auth_submission_contact: "zhaoqy@example.edu",
        auth_submission_note: "评测样例：聚会桌游发起人",
        auth_submitted_at: now,
        auth_review_reason: "",
        auth_reviewed_at: now,
        password_hash: hashPassword(DEFAULT_INITIAL_PASSWORD),
        created_at: now,
      },
      {
        id: "11007",
        student_no: "2314077",
        name: "周昊然",
        nickname: "Haoran",
        role: "student",
        avatar: "7.png",
        auth_status: "verified",
        credit_score: 83,
        status: "active",
        tags: ["阵营", "社交", "狼人杀"],
        contact: "zhouhr@example.edu",
        auth_submission_name: "周昊然",
        auth_submission_student_no: "2314077",
        auth_submission_contact: "zhouhr@example.edu",
        auth_submission_note: "评测样例：阵营社交类玩家",
        auth_submitted_at: now,
        auth_review_reason: "",
        auth_reviewed_at: now,
        password_hash: hashPassword(DEFAULT_INITIAL_PASSWORD),
        created_at: now,
      },
      {
        id: "11008",
        student_no: "2314088",
        name: "林晓雯",
        nickname: "Xiaowen",
        role: "student",
        avatar: "8.png",
        auth_status: "pending",
        credit_score: 100,
        status: "active",
        tags: ["剧本杀", "情感"],
        contact: "linxw@example.edu",
        auth_submission_name: "林晓雯",
        auth_submission_student_no: "2314088",
        auth_submission_contact: "linxw@example.edu",
        auth_submission_note: "评测样例：等待管理员审核的新用户",
        auth_submitted_at: now,
        auth_review_reason: "",
        auth_reviewed_at: null,
        password_hash: hashPassword(DEFAULT_INITIAL_PASSWORD),
        created_at: now,
      },
      {
        id: "11009",
        student_no: "2314099",
        name: "王嘉宁",
        nickname: "BannedDemo",
        role: "student",
        avatar: "9.png",
        auth_status: "verified",
        credit_score: 70,
        status: "banned",
        status_reason: "评测样例：账号封禁展示",
        tags: ["违规样例"],
        contact: "wangjn@example.edu",
        auth_submission_name: "王嘉宁",
        auth_submission_student_no: "2314099",
        auth_submission_contact: "wangjn@example.edu",
        auth_submission_note: "评测样例：封禁账号",
        auth_submitted_at: now,
        auth_review_reason: "",
        auth_reviewed_at: now,
        password_hash: hashPassword(DEFAULT_INITIAL_PASSWORD),
        created_at: now,
      },
      {
        id: "11010",
        student_no: "2314100",
        name: "许一诺",
        nickname: "LimitedDemo",
        role: "student",
        avatar: "10.png",
        auth_status: "verified",
        credit_score: 76,
        status: "limited",
        status_reason: "评测样例：受限账号不可发布组局",
        tags: ["受限样例"],
        contact: "xuyn@example.edu",
        auth_submission_name: "许一诺",
        auth_submission_student_no: "2314100",
        auth_submission_contact: "xuyn@example.edu",
        auth_submission_note: "评测样例：受限账号",
        auth_submitted_at: now,
        auth_review_reason: "",
        auth_reviewed_at: now,
        password_hash: hashPassword(DEFAULT_INITIAL_PASSWORD),
        created_at: now,
      },
      {
        id: "10001",
        student_no: "2311987",
        name: "史傅冠华",
        nickname: "系统管理员",
        role: "admin",
        avatar: "adm.png",
        auth_status: "verified",
        credit_score: 100,
        status: "active",
        tags: ["管理"],
        contact: "admin@example.edu",
        auth_submission_name: "",
        auth_submission_student_no: "",
        auth_submission_contact: "",
        auth_submission_note: "",
        auth_submitted_at: null,
        auth_review_reason: "",
        auth_reviewed_at: null,
        password_hash: hashPassword(DEFAULT_INITIAL_PASSWORD),
        created_at: now,
      },
      {
        id: "10002",
        student_no: "venue001",
        name: "场地管理员",
        nickname: "社团空间管理员",
        role: "venue_admin",
        avatar: "adm.png",
        auth_status: "verified",
        credit_score: 100,
        status: "active",
        tags: ["场地"],
        contact: "venue@example.edu",
        auth_submission_name: "",
        auth_submission_student_no: "",
        auth_submission_contact: "",
        auth_submission_note: "",
        auth_submitted_at: null,
        auth_review_reason: "",
        auth_reviewed_at: null,
        password_hash: hashPassword(DEFAULT_INITIAL_PASSWORD),
        created_at: now,
      },
    ],
    game_libs: [
      {
        id: "g1",
        name: "阿瓦隆",
        type: "桌游",
        min_players: 5,
        max_players: 10,
        duration_minutes: 90,
        difficulty: "中等",
        description: "阵营推理类桌游，适合熟人破冰与策略交流。",
        tags: ["阵营", "推理"],
        status: "active",
      },
      {
        id: "g2",
        name: "卡坦岛",
        type: "桌游",
        min_players: 3,
        max_players: 4,
        duration_minutes: 120,
        difficulty: "中等",
        description: "资源经营与交易策略类桌游。",
        tags: ["德式", "策略"],
        status: "active",
      },
      {
        id: "g3",
        name: "年轮",
        type: "剧本杀",
        min_players: 6,
        max_players: 6,
        duration_minutes: 240,
        difficulty: "进阶",
        description: "情感推理本，需要 DM 主持与固定人数。",
        tags: ["推理", "情感", "DM"],
        status: "active",
      },
      {
        id: "g4",
        name: "只言片语",
        type: "聚会桌游",
        min_players: 3,
        max_players: 8,
        duration_minutes: 45,
        difficulty: "新手",
        description: "轻量表达与想象类聚会游戏，适合破冰和轻松交流。",
        tags: ["聚会", "想象", "表达"],
        status: "active",
      },
      {
        id: "g5",
        name: "花火",
        type: "合作桌游",
        min_players: 2,
        max_players: 5,
        duration_minutes: 40,
        difficulty: "新手",
        description: "合作沟通与有限信息推理游戏，适合新手入门。",
        tags: ["合作", "新手", "轻策略"],
        status: "active",
      },
      {
        id: "g6",
        name: "狼人杀",
        type: "桌游",
        min_players: 8,
        max_players: 12,
        duration_minutes: 120,
        difficulty: "中等",
        description: "发言、社交与阵营对抗类游戏，适合大人数活动。",
        tags: ["阵营", "社交", "发言"],
        status: "active",
      },
      {
        id: "g7",
        name: "跑团导入短章",
        type: "跑团",
        min_players: 3,
        max_players: 6,
        duration_minutes: 180,
        difficulty: "进阶",
        description: "短篇角色扮演导入模组，适合体验叙事型活动。",
        tags: ["角色扮演", "剧情", "新手"],
        status: "active",
      },
      {
        id: "g8",
        name: "落日剧场",
        type: "剧本杀",
        min_players: 6,
        max_players: 7,
        duration_minutes: 240,
        difficulty: "进阶",
        description: "评测样例：已下架剧本，不应出现在普通发布选择中。",
        tags: ["推理", "沉浸"],
        status: "inactive",
      },
    ],
    game_sessions: [
      {
        id: "s1",
        host_id: "11001",
        game_id: "g1",
        title: "周五晚阿瓦隆缺三人",
        description: "新老玩家都可，要求准时到场，现场讲规则。",
        start_time: firstSessionStart.toISOString(),
        end_time: addHours(firstSessionStart, 3).toISOString(),
        location: "学生活动中心三楼",
        max_members: 6,
        current_members: 1,
        min_credit_required: 80,
        join_mode: "manual",
        status: "recruiting",
        venue_status: "none",
        created_at: now,
      },
      {
        id: "s2",
        host_id: "11002",
        game_id: "g2",
        title: "卡坦岛新手教学局",
        description: "已有一套实体桌游，欢迎没玩过的同学。",
        start_time: secondSessionStart.toISOString(),
        end_time: addHours(secondSessionStart, 3).toISOString(),
        location: "二主楼公共讨论区",
        max_members: 4,
        current_members: 1,
        min_credit_required: 75,
        join_mode: "direct",
        status: "recruiting",
        venue_status: "none",
        created_at: now,
      },
      {
        id: "s3",
        host_id: "11005",
        game_id: "g5",
        title: "午休花火合作新手局",
        description: "时间短、规则轻，适合午休体验合作桌游。",
        start_time: lunchSessionStart.toISOString(),
        end_time: addHours(lunchSessionStart, 1.5).toISOString(),
        location: "图书馆咖啡区",
        max_members: 5,
        current_members: 1,
        min_credit_required: 60,
        join_mode: "direct",
        status: "recruiting",
        venue_status: "none",
        created_at: now,
      },
      {
        id: "s4",
        host_id: "11006",
        game_id: "g4",
        title: "周三只言片语欢乐局",
        description: "不卷胜负，主打轻松破冰和脑洞表达。",
        start_time: partySessionStart.toISOString(),
        end_time: addHours(partySessionStart, 2).toISOString(),
        location: "新开湖畔讨论区",
        max_members: 8,
        current_members: 2,
        min_credit_required: 70,
        join_mode: "direct",
        status: "recruiting",
        venue_status: "none",
        created_at: now,
      },
      {
        id: "s5",
        host_id: "11007",
        game_id: "g6",
        title: "狼人杀十二人热场局",
        description: "适合喜欢发言和阵营博弈的同学，满 8 人开。",
        start_time: socialSessionStart.toISOString(),
        end_time: addHours(socialSessionStart, 3).toISOString(),
        location: "学生活动中心大厅",
        max_members: 12,
        current_members: 1,
        min_credit_required: 70,
        join_mode: "direct",
        status: "recruiting",
        venue_status: "none",
        created_at: now,
      },
      {
        id: "s6",
        host_id: "11005",
        game_id: "g3",
        title: "年轮沉浸剧本杀固定车",
        description: "偏情感和推理，预计四小时，请确认时间充裕。",
        start_time: scriptSessionStart.toISOString(),
        end_time: addHours(scriptSessionStart, 4).toISOString(),
        location: "社团活动室 B201",
        max_members: 6,
        current_members: 3,
        min_credit_required: 85,
        join_mode: "manual",
        status: "recruiting",
        venue_status: "none",
        created_at: now,
      },
      {
        id: "s7",
        host_id: "11006",
        game_id: "g2",
        title: "卡坦岛进阶交易局",
        description: "希望熟悉规则的玩家加入，重点体验交易谈判。",
        start_time: strategySessionStart.toISOString(),
        end_time: addHours(strategySessionStart, 3).toISOString(),
        location: "二主楼公共讨论区",
        max_members: 4,
        current_members: 2,
        min_credit_required: 90,
        join_mode: "manual",
        status: "recruiting",
        venue_status: "none",
        created_at: now,
      },
      {
        id: "s8",
        host_id: "11005",
        game_id: "g5",
        title: "花火满员挑战局",
        description: "评测样例：满员状态，不在默认大厅继续招募。",
        start_time: fullSessionStart.toISOString(),
        end_time: addHours(fullSessionStart, 2).toISOString(),
        location: "图书馆研讨间 2",
        max_members: 5,
        current_members: 5,
        min_credit_required: 80,
        join_mode: "direct",
        status: "full",
        venue_status: "none",
        created_at: now,
      },
      {
        id: "s9",
        host_id: "11005",
        game_id: "g5",
        title: "已完成花火互评样例局",
        description: "评测样例：已完成状态，可查看互评展示。",
        start_time: finishedSessionStart.toISOString(),
        end_time: addHours(finishedSessionStart, 2).toISOString(),
        location: "学生活动中心 302",
        max_members: 5,
        current_members: 2,
        min_credit_required: 70,
        join_mode: "direct",
        status: "finished",
        venue_status: "none",
        created_at: now,
        updated_at: now,
      },
      {
        id: "s10",
        host_id: "11006",
        game_id: "g4",
        title: "未组局成功样例局",
        description: "评测样例：活动开始后由发起人标记未组局成功。",
        start_time: failedSessionStart.toISOString(),
        end_time: addHours(failedSessionStart, 2).toISOString(),
        location: "新开湖畔讨论区",
        max_members: 8,
        current_members: 1,
        min_credit_required: 70,
        join_mode: "direct",
        status: "failed",
        venue_status: "cancelled",
        fail_reason: "人数不足",
        created_at: now,
        updated_at: now,
      },
      {
        id: "s11",
        host_id: "11007",
        game_id: "g6",
        title: "临时取消狼人杀样例局",
        description: "评测样例：取消状态，用于管理员和个人中心查看历史。",
        start_time: cancelledSessionStart.toISOString(),
        end_time: addHours(cancelledSessionStart, 3).toISOString(),
        location: "学生活动中心大厅",
        max_members: 12,
        current_members: 1,
        min_credit_required: 70,
        join_mode: "direct",
        status: "cancelled",
        venue_status: "none",
        cancel_reason: "场地临时不可用",
        created_at: now,
        updated_at: now,
      },
      {
        id: "s12",
        host_id: "11006",
        game_id: "g7",
        title: "跑团导入短章体验",
        description: "第一次跑团也可参加，主持人会提供角色卡和规则说明。",
        start_time: rpgSessionStart.toISOString(),
        end_time: addHours(rpgSessionStart, 3).toISOString(),
        location: "线上语音 + 二主楼讨论区",
        max_members: 6,
        current_members: 1,
        min_credit_required: 80,
        join_mode: "manual",
        status: "recruiting",
        venue_status: "none",
        created_at: now,
      },
    ],
    session_applications: [
      {
        id: "a1",
        session_id: "s6",
        applicant_id: "11008",
        message: "我想体验情感推理本，时间可以配合。",
        status: "pending",
        apply_time: now,
        review_time: null,
        review_reason: "",
      },
      {
        id: "a2",
        session_id: "s7",
        applicant_id: "11007",
        message: "想加入进阶局练习交易。",
        status: "rejected",
        apply_time: now,
        review_time: now,
        review_reason: "本局优先熟悉卡坦岛规则的玩家",
      },
    ],
    session_members: [
      {
        id: "m1",
        session_id: "s1",
        user_id: "11001",
        member_role: "host",
        join_time: now,
      },
      {
        id: "m2",
        session_id: "s2",
        user_id: "11002",
        member_role: "host",
        join_time: now,
      },
      {
        id: "m3",
        session_id: "s3",
        user_id: "11005",
        member_role: "host",
        join_time: now,
      },
      {
        id: "m4",
        session_id: "s4",
        user_id: "11006",
        member_role: "host",
        join_time: now,
      },
      {
        id: "m5",
        session_id: "s4",
        user_id: "11005",
        member_role: "player",
        join_time: now,
      },
      {
        id: "m6",
        session_id: "s5",
        user_id: "11007",
        member_role: "host",
        join_time: now,
      },
      {
        id: "m7",
        session_id: "s6",
        user_id: "11005",
        member_role: "host",
        join_time: now,
      },
      {
        id: "m8",
        session_id: "s6",
        user_id: "11006",
        member_role: "player",
        join_time: now,
      },
      {
        id: "m9",
        session_id: "s6",
        user_id: "11007",
        member_role: "player",
        join_time: now,
      },
      {
        id: "m10",
        session_id: "s7",
        user_id: "11006",
        member_role: "host",
        join_time: now,
      },
      {
        id: "m11",
        session_id: "s7",
        user_id: "11005",
        member_role: "player",
        join_time: now,
      },
      {
        id: "m12",
        session_id: "s8",
        user_id: "11005",
        member_role: "host",
        join_time: now,
      },
      {
        id: "m13",
        session_id: "s8",
        user_id: "11006",
        member_role: "player",
        join_time: now,
      },
      {
        id: "m14",
        session_id: "s8",
        user_id: "11007",
        member_role: "player",
        join_time: now,
      },
      {
        id: "m15",
        session_id: "s8",
        user_id: "11001",
        member_role: "player",
        join_time: now,
      },
      {
        id: "m16",
        session_id: "s8",
        user_id: "11002",
        member_role: "player",
        join_time: now,
      },
      {
        id: "m17",
        session_id: "s9",
        user_id: "11005",
        member_role: "host",
        join_time: now,
      },
      {
        id: "m18",
        session_id: "s9",
        user_id: "11006",
        member_role: "player",
        join_time: now,
      },
      {
        id: "m19",
        session_id: "s10",
        user_id: "11006",
        member_role: "host",
        join_time: now,
      },
      {
        id: "m20",
        session_id: "s11",
        user_id: "11007",
        member_role: "host",
        join_time: now,
      },
      {
        id: "m21",
        session_id: "s12",
        user_id: "11006",
        member_role: "host",
        join_time: now,
      },
    ],
    venues: [
      {
        id: "v1",
        name: "学生活动中心 302",
        location: "学生活动中心三楼",
        capacity: 12,
        manager_id: "10002",
        available_time: "周一至周日 09:00-22:30",
        open_rules: "需提前一天申请；剧本杀需保持安静并恢复桌椅。",
        status: "active",
        description: "适合桌游、剧本杀和社团小型活动。",
      },
      {
        id: "v2",
        name: "社团活动室 B201",
        location: "大学生活动中心 B 区二楼",
        capacity: 8,
        manager_id: "10002",
        available_time: "周五 18:00-22:30；周末 09:00-22:30",
        open_rules: "考试周暂停预约。",
        status: "active",
        description: "小型桌游与推理活动空间。",
      },
    ],
    venue_reservations: [],
    reviews: [
      {
        id: "r1",
        session_id: "s9",
        reviewer_id: "11005",
        target_user_id: "11006",
        score: 5,
        content: "沟通顺畅，合作思路清晰。",
        created_at: now,
      },
      {
        id: "r2",
        session_id: "s9",
        reviewer_id: "11006",
        target_user_id: "11005",
        score: 4,
        content: "组织准时，规则说明清楚。",
        created_at: now,
      },
    ],
    credit_records: [],
    complaints: [],
    notifications: [],
    admin_logs: [],
    auth_sessions: [],
  };
}

function futureDate(daysFromNow, hour) {
  const date = new Date(Date.now() + daysFromNow * 24 * 60 * 60 * 1000);
  date.setHours(hour, 0, 0, 0);
  return date;
}

function pastDate(daysAgo, hour) {
  const date = new Date(Date.now() - daysAgo * 24 * 60 * 60 * 1000);
  date.setHours(hour, 0, 0, 0);
  return date;
}

function addHours(date, hours) {
  return new Date(date.getTime() + hours * 60 * 60 * 1000);
}

module.exports = { createSeedData };
