const { nowIso } = require("../utils");

function createSeedData() {
  const now = nowIso();
  return {
    users: [
      {
        id: "11001",
        student_no: "2314007",
        name: "李佳璞",
        nickname: "Jiapu",
        role: "student",
        avatar: "1.png",
        auth_status: "verified",
        credit_score: 100,
        status: "active",
        tags: ["推理", "阵营", "欢乐本"],
        contact: "lijia@example.edu",
        auth_submission_name: "李佳璞",
        auth_submission_student_no: "2314007",
        auth_submission_contact: "lijia@example.edu",
        auth_submission_note: "已通过历史导入认证",
        auth_submitted_at: now,
        auth_review_reason: "",
        auth_reviewed_at: now,
        created_at: now,
      },
      {
        id: "11002",
        student_no: "2313983",
        name: "刘砚桐",
        nickname: "YanTong",
        role: "student",
        avatar: "2.png",
        auth_status: "verified",
        credit_score: 96,
        status: "active",
        tags: ["德式桌游", "策略"],
        contact: "liuyt@example.edu",
        auth_submission_name: "刘砚桐",
        auth_submission_student_no: "2313983",
        auth_submission_contact: "liuyt@example.edu",
        auth_submission_note: "已通过历史导入认证",
        auth_submitted_at: now,
        auth_review_reason: "",
        auth_reviewed_at: now,
        created_at: now,
      },
      {
        id: "11003",
        student_no: "2313828",
        name: "苏雨辰",
        nickname: "Yuchen",
        role: "student",
        avatar: "3.png",
        auth_status: "pending",
        credit_score: 100,
        status: "active",
        tags: ["新手友好"],
        contact: "suyc@example.edu",
        auth_submission_name: "苏雨辰",
        auth_submission_student_no: "2313828",
        auth_submission_contact: "suyc@example.edu",
        auth_submission_note: "首次提交学生证信息，等待管理员审核。",
        auth_submitted_at: now,
        auth_review_reason: "",
        auth_reviewed_at: null,
        created_at: now,
      },
      {
        id: "11004",
        student_no: "2312194",
        name: "朱乐晨",
        nickname: "Lechen",
        role: "student",
        avatar: "4.png",
        auth_status: "unverified",
        credit_score: 92,
        status: "active",
        tags: ["剧本杀", "硬核"],
        contact: "zhulc@example.edu",
        auth_submission_name: "朱乐晨",
        auth_submission_student_no: "2312194",
        auth_submission_contact: "zhulc@example.edu",
        auth_submission_note: "已通过历史导入认证",
        auth_submitted_at: now,
        auth_review_reason: "",
        auth_reviewed_at: null,
        created_at: now,
      },
      {
        id: "10001",
        student_no: "2311987",
        name: "史傅冠华",
        nickname: "系统管理员",
        role: "admin",
        avatar: "adm.png",
        auth_status: "verified",
        credit_score: 100,
        status: "active",
        tags: ["管理"],
        contact: "admin@example.edu",
        auth_submission_name: "",
        auth_submission_student_no: "",
        auth_submission_contact: "",
        auth_submission_note: "",
        auth_submitted_at: null,
        auth_review_reason: "",
        auth_reviewed_at: null,
        created_at: now,
      },
      {
        id: "10002",
        student_no: "venue001",
        name: "场地管理员",
        nickname: "社团空间管理员",
        role: "venue_admin",
        avatar: "adm.png",
        auth_status: "verified",
        credit_score: 100,
        status: "active",
        tags: ["场地"],
        contact: "venue@example.edu",
        auth_submission_name: "",
        auth_submission_student_no: "",
        auth_submission_contact: "",
        auth_submission_note: "",
        auth_submitted_at: null,
        auth_review_reason: "",
        auth_reviewed_at: null,
        created_at: now,
      },
    ],
    game_libs: [
      {
        id: "g1",
        name: "阿瓦隆",
        type: "桌游",
        min_players: 5,
        max_players: 10,
        duration_minutes: 90,
        difficulty: "中等",
        description: "阵营推理类桌游，适合熟人破冰与策略交流。",
        tags: ["阵营", "推理"],
        status: "active",
      },
      {
        id: "g2",
        name: "卡坦岛",
        type: "桌游",
        min_players: 3,
        max_players: 4,
        duration_minutes: 120,
        difficulty: "中等",
        description: "资源经营与交易策略类桌游。",
        tags: ["德式", "策略"],
        status: "active",
      },
      {
        id: "g3",
        name: "年轮",
        type: "剧本杀",
        min_players: 6,
        max_players: 6,
        duration_minutes: 240,
        difficulty: "进阶",
        description: "情感推理本，需要 DM 主持与固定人数。",
        tags: ["推理", "情感", "DM"],
        status: "active",
      },
    ],
    game_sessions: [
      {
        id: "s1",
        host_id: "11001",
        game_id: "g1",
        title: "周五晚阿瓦隆缺三人",
        description: "新老玩家都可，要求准时到场，现场讲规则。",
        start_time: "2026-06-07T19:00:00.000+08:00",
        end_time: "2026-06-07T22:00:00.000+08:00",
        location: "学生活动中心三楼",
        max_members: 6,
        current_members: 1,
        min_credit_required: 80,
        join_mode: "manual",
        status: "recruiting",
        venue_status: "none",
        created_at: now,
      },
      {
        id: "s2",
        host_id: "11002",
        game_id: "g2",
        title: "卡坦岛新手教学局",
        description: "已有一套实体桌游，欢迎没玩过的同学。",
        start_time: "2026-06-08T14:00:00.000+08:00",
        end_time: "2026-06-08T17:00:00.000+08:00",
        location: "二主楼公共讨论区",
        max_members: 4,
        current_members: 1,
        min_credit_required: 75,
        join_mode: "direct",
        status: "recruiting",
        venue_status: "none",
        created_at: now,
      },
    ],
    session_applications: [],
    session_members: [
      {
        id: "m1",
        session_id: "s1",
        user_id: "11001",
        member_role: "host",
        join_time: now,
        checkin_status: "pending",
      },
      {
        id: "m2",
        session_id: "s2",
        user_id: "11002",
        member_role: "host",
        join_time: now,
        checkin_status: "pending",
      },
    ],
    venues: [
      {
        id: "v1",
        name: "学生活动中心 302",
        location: "学生活动中心三楼",
        capacity: 12,
        manager_id: "10002",
        available_time: "周一至周日 09:00-22:30",
        open_rules: "需提前一天申请；剧本杀需保持安静并恢复桌椅。",
        status: "active",
        description: "适合桌游、剧本杀和社团小型活动。",
      },
      {
        id: "v2",
        name: "社团活动室 B201",
        location: "大学生活动中心 B 区二楼",
        capacity: 8,
        manager_id: "10002",
        available_time: "周五 18:00-22:30；周末 09:00-22:30",
        open_rules: "考试周暂停预约。",
        status: "active",
        description: "小型桌游与推理活动空间。",
      },
    ],
    venue_reservations: [],
    reviews: [],
    credit_records: [],
    complaints: [],
    notifications: [],
    admin_logs: [],
  };
}

module.exports = { createSeedData };
